/**
 * DO NOT MODIFY!
 * 
 * Automatically generated by tscss.
 */

export const header: string;
export const title: string;
export const backButton: string;
export const hidden: string;
export const backButtonImage: string;
