/**
 * DO NOT MODIFY!
 * 
 * Automatically generated by tscss.
 */

export const bubbles: string;
export const bubble: string;
export const open: string;
export const category: string;
export const amount: string;
